// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Darp.Luau.Native
{
    public static unsafe partial class LuauNative
    {
        const string __DllName = "luau";

        public const uint LUA_USE_LONGJMP = 0;
        public const uint LUA_IDSIZE = 256;
        public const uint LUA_MINSTACK = 20;
        public const uint LUAI_MAXCSTACK = 8000;
        public const uint LUAI_MAXCALLS = 20000;
        public const uint LUAI_MAXCCALLS = 200;
        public const uint LUA_BUFFERSIZE = 512;
        public const uint LUA_UTAG_LIMIT = 128;
        public const uint LUA_LUTAG_LIMIT = 128;
        public const uint LUA_SIZECLASSES = 40;
        public const uint LUA_MEMORY_CATEGORIES = 256;
        public const uint LUA_EXECUTION_CALLBACK_STORAGE = 512;
        public const uint LUA_MINSTRTABSIZE = 32;
        public const uint LUA_MAXCAPTURES = 32;
        public const uint LUA_VECTOR_SIZE = 3;
        public const uint LUA_EXTRA_SIZE = 1;
        public const uint LUA_REFNIL = 0;
        public static ReadOnlySpan<byte> LUA_COLIBNAME => new byte[] { 99, 111, 114, 111, 117, 116, 105, 110, 101, 0 };
        public static ReadOnlySpan<byte> LUA_TABLIBNAME => new byte[] { 116, 97, 98, 108, 101, 0 };
        public static ReadOnlySpan<byte> LUA_OSLIBNAME => new byte[] { 111, 115, 0 };
        public static ReadOnlySpan<byte> LUA_STRLIBNAME => new byte[] { 115, 116, 114, 105, 110, 103, 0 };
        public static ReadOnlySpan<byte> LUA_BITLIBNAME => new byte[] { 98, 105, 116, 51, 50, 0 };
        public static ReadOnlySpan<byte> LUA_BUFFERLIBNAME => new byte[] { 98, 117, 102, 102, 101, 114, 0 };
        public static ReadOnlySpan<byte> LUA_UTF8LIBNAME => new byte[] { 117, 116, 102, 56, 0 };
        public static ReadOnlySpan<byte> LUA_MATHLIBNAME => new byte[] { 109, 97, 116, 104, 0 };
        public static ReadOnlySpan<byte> LUA_DBLIBNAME => new byte[] { 100, 101, 98, 117, 103, 0 };
        public static ReadOnlySpan<byte> LUA_VECLIBNAME => new byte[] { 118, 101, 99, 116, 111, 114, 0 };




        [DllImport(__DllName, EntryPoint = "lua_newstate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* lua_newstate(delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint, void*> f, void* ud);

        [DllImport(__DllName, EntryPoint = "lua_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_close(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_newthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* lua_newthread(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_mainthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* lua_mainthread(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_resetthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_resetthread(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_isthreadreset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isthreadreset(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_absindex", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_absindex(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_gettop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_gettop(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_settop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_settop(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_pushvalue", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushvalue(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_remove", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_remove(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_insert", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_insert(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_replace", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_replace(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_checkstack", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_checkstack(lua_State* L, int sz);

        [DllImport(__DllName, EntryPoint = "lua_rawcheckstack", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rawcheckstack(lua_State* L, int sz);

        [DllImport(__DllName, EntryPoint = "lua_xmove", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_xmove(lua_State* from, lua_State* to, int n);

        [DllImport(__DllName, EntryPoint = "lua_xpush", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_xpush(lua_State* from, lua_State* to, int idx);

        [DllImport(__DllName, EntryPoint = "lua_isnumber", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isnumber(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_isstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isstring(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_iscfunction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_iscfunction(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_isLfunction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isLfunction(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_isuserdata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isuserdata(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_type", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_type(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_typename", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_typename(lua_State* L, int tp);

        [DllImport(__DllName, EntryPoint = "lua_equal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_equal(lua_State* L, int idx1, int idx2);

        [DllImport(__DllName, EntryPoint = "lua_rawequal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawequal(lua_State* L, int idx1, int idx2);

        [DllImport(__DllName, EntryPoint = "lua_lessthan", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_lessthan(lua_State* L, int idx1, int idx2);

        [DllImport(__DllName, EntryPoint = "lua_tonumberx", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double lua_tonumberx(lua_State* L, int idx, int* isnum);

        [DllImport(__DllName, EntryPoint = "lua_tointegerx", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_tointegerx(lua_State* L, int idx, int* isnum);

        [DllImport(__DllName, EntryPoint = "lua_tounsignedx", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint lua_tounsignedx(lua_State* L, int idx, int* isnum);

        [DllImport(__DllName, EntryPoint = "lua_tovector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float* lua_tovector(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_toboolean", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_toboolean(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_tolstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_tolstring(lua_State* L, int idx, nuint* len);

        [DllImport(__DllName, EntryPoint = "lua_tostringatom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_tostringatom(lua_State* L, int idx, int* atom);

        [DllImport(__DllName, EntryPoint = "lua_tolstringatom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_tolstringatom(lua_State* L, int idx, nuint* len, int* atom);

        [DllImport(__DllName, EntryPoint = "lua_namecallatom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_namecallatom(lua_State* L, int* atom);

        [DllImport(__DllName, EntryPoint = "lua_objlen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_objlen(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_tocfunction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern delegate* unmanaged[Cdecl]<lua_State*, int> lua_tocfunction(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_tolightuserdata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_tolightuserdata(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_tolightuserdatatagged", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_tolightuserdatatagged(lua_State* L, int idx, int tag);

        [DllImport(__DllName, EntryPoint = "lua_touserdata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_touserdata(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_touserdatatagged", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_touserdatatagged(lua_State* L, int idx, int tag);

        [DllImport(__DllName, EntryPoint = "lua_userdatatag", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_userdatatag(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_lightuserdatatag", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_lightuserdatatag(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_tothread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* lua_tothread(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_tobuffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_tobuffer(lua_State* L, int idx, nuint* len);

        [DllImport(__DllName, EntryPoint = "lua_topointer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_topointer(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_pushnil", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushnil(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_pushnumber", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushnumber(lua_State* L, double n);

        [DllImport(__DllName, EntryPoint = "lua_pushinteger", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushinteger(lua_State* L, int n);

        [DllImport(__DllName, EntryPoint = "lua_pushunsigned", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushunsigned(lua_State* L, uint n);

        [DllImport(__DllName, EntryPoint = "lua_pushvector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushvector(lua_State* L, float x, float y, float z);

        [DllImport(__DllName, EntryPoint = "lua_pushlstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushlstring(lua_State* L, byte* s, nuint l);

        [DllImport(__DllName, EntryPoint = "lua_pushstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushstring(lua_State* L, byte* s);

        [DllImport(__DllName, EntryPoint = "lua_pushvfstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_pushvfstring(lua_State* L, byte* fmt, byte* argp);

        [DllImport(__DllName, EntryPoint = "lua_pushfstringL", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_pushfstringL(lua_State* L, byte* fmt);

        [DllImport(__DllName, EntryPoint = "lua_pushcclosurek", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushcclosurek(lua_State* L, delegate* unmanaged[Cdecl]<lua_State*, int> fn_, byte* debugname, int nup, delegate* unmanaged[Cdecl]<lua_State*, int, int> cont);

        [DllImport(__DllName, EntryPoint = "lua_pushboolean", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushboolean(lua_State* L, int b);

        [DllImport(__DllName, EntryPoint = "lua_pushthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_pushthread(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_pushlightuserdatatagged", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushlightuserdatatagged(lua_State* L, void* p, int tag);

        [DllImport(__DllName, EntryPoint = "lua_newuserdatatagged", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_newuserdatatagged(lua_State* L, nuint sz, int tag);

        [DllImport(__DllName, EntryPoint = "lua_newuserdatataggedwithmetatable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_newuserdatataggedwithmetatable(lua_State* L, nuint sz, int tag);

        [DllImport(__DllName, EntryPoint = "lua_newuserdatadtor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_newuserdatadtor(lua_State* L, nuint sz, delegate* unmanaged[Cdecl]<void*, void> dtor);

        [DllImport(__DllName, EntryPoint = "lua_newbuffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_newbuffer(lua_State* L, nuint sz);

        [DllImport(__DllName, EntryPoint = "lua_gettable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_gettable(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_getfield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getfield(lua_State* L, int idx, byte* k);

        [DllImport(__DllName, EntryPoint = "lua_rawgetfield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawgetfield(lua_State* L, int idx, byte* k);

        [DllImport(__DllName, EntryPoint = "lua_rawget", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawget(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_rawgeti", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawgeti(lua_State* L, int idx, int n);

        [DllImport(__DllName, EntryPoint = "lua_rawgetptagged", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawgetptagged(lua_State* L, int idx, void* p, int tag);

        [DllImport(__DllName, EntryPoint = "lua_createtable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_createtable(lua_State* L, int narr, int nrec);

        [DllImport(__DllName, EntryPoint = "lua_setreadonly", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setreadonly(lua_State* L, int idx, int enabled);

        [DllImport(__DllName, EntryPoint = "lua_getreadonly", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getreadonly(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_setsafeenv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setsafeenv(lua_State* L, int idx, int enabled);

        [DllImport(__DllName, EntryPoint = "lua_getmetatable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getmetatable(lua_State* L, int objindex);

        [DllImport(__DllName, EntryPoint = "lua_getfenv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_getfenv(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_settable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_settable(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_setfield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setfield(lua_State* L, int idx, byte* k);

        [DllImport(__DllName, EntryPoint = "lua_rawsetfield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rawsetfield(lua_State* L, int idx, byte* k);

        [DllImport(__DllName, EntryPoint = "lua_rawset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rawset(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_rawseti", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rawseti(lua_State* L, int idx, int n);

        [DllImport(__DllName, EntryPoint = "lua_rawsetptagged", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rawsetptagged(lua_State* L, int idx, void* p, int tag);

        [DllImport(__DllName, EntryPoint = "lua_setmetatable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_setmetatable(lua_State* L, int objindex);

        [DllImport(__DllName, EntryPoint = "lua_setfenv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_setfenv(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "luau_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_load(lua_State* L, byte* chunkname, byte* data, nuint size, int env);

        [DllImport(__DllName, EntryPoint = "lua_call", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_call(lua_State* L, int nargs, int nresults);

        [DllImport(__DllName, EntryPoint = "lua_pcall", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_pcall(lua_State* L, int nargs, int nresults, int errfunc);

        [DllImport(__DllName, EntryPoint = "lua_cpcall", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_cpcall(lua_State* L, delegate* unmanaged[Cdecl]<lua_State*, int> func, void* ud);

        [DllImport(__DllName, EntryPoint = "lua_yield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_yield(lua_State* L, int nresults);

        [DllImport(__DllName, EntryPoint = "lua_break", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_break(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_resume", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_resume(lua_State* L, lua_State* from, int narg);

        [DllImport(__DllName, EntryPoint = "lua_resumeerror", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_resumeerror(lua_State* L, lua_State* from);

        [DllImport(__DllName, EntryPoint = "lua_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_status(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_isyieldable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isyieldable(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_getthreaddata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_getthreaddata(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_setthreaddata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setthreaddata(lua_State* L, void* data);

        [DllImport(__DllName, EntryPoint = "lua_costatus", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_costatus(lua_State* L, lua_State* co);

        [DllImport(__DllName, EntryPoint = "lua_gc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_gc(lua_State* L, int what, int data);

        [DllImport(__DllName, EntryPoint = "lua_setmemcat", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setmemcat(lua_State* L, int category);

        [DllImport(__DllName, EntryPoint = "lua_totalbytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern nuint lua_totalbytes(lua_State* L, int category);

        [DllImport(__DllName, EntryPoint = "lua_next", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_next(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_rawiter", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawiter(lua_State* L, int idx, int iter);

        [DllImport(__DllName, EntryPoint = "lua_concat", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_concat(lua_State* L, int n);

        [DllImport(__DllName, EntryPoint = "lua_encodepointer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern nuint lua_encodepointer(lua_State* L, nuint p);

        [DllImport(__DllName, EntryPoint = "lua_clock", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double lua_clock();

        [DllImport(__DllName, EntryPoint = "lua_setuserdatatag", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setuserdatatag(lua_State* L, int idx, int tag);

        [DllImport(__DllName, EntryPoint = "lua_setuserdatadtor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setuserdatadtor(lua_State* L, int tag, delegate* unmanaged[Cdecl]<lua_State*, void*, void> dtor);

        [DllImport(__DllName, EntryPoint = "lua_getuserdatadtor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern delegate* unmanaged[Cdecl]<lua_State*, void*, void> lua_getuserdatadtor(lua_State* L, int tag);

        [DllImport(__DllName, EntryPoint = "lua_setuserdatametatable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setuserdatametatable(lua_State* L, int tag);

        [DllImport(__DllName, EntryPoint = "lua_getuserdatametatable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_getuserdatametatable(lua_State* L, int tag);

        [DllImport(__DllName, EntryPoint = "lua_setlightuserdataname", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setlightuserdataname(lua_State* L, int tag, byte* name);

        [DllImport(__DllName, EntryPoint = "lua_getlightuserdataname", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_getlightuserdataname(lua_State* L, int tag);

        [DllImport(__DllName, EntryPoint = "lua_clonefunction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_clonefunction(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_cleartable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_cleartable(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_clonetable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_clonetable(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_getallocf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint, void*> lua_getallocf(lua_State* L, void** ud);

        [DllImport(__DllName, EntryPoint = "lua_ref", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_ref(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "lua_unref", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_unref(lua_State* L, int ref_);

        [DllImport(__DllName, EntryPoint = "lua_stackdepth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_stackdepth(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_getinfo", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getinfo(lua_State* L, int level, byte* what, lua_Debug* ar);

        [DllImport(__DllName, EntryPoint = "lua_getargument", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getargument(lua_State* L, int level, int n);

        [DllImport(__DllName, EntryPoint = "lua_getlocal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_getlocal(lua_State* L, int level, int n);

        [DllImport(__DllName, EntryPoint = "lua_setlocal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_setlocal(lua_State* L, int level, int n);

        [DllImport(__DllName, EntryPoint = "lua_getupvalue", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_getupvalue(lua_State* L, int funcindex, int n);

        [DllImport(__DllName, EntryPoint = "lua_setupvalue", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_setupvalue(lua_State* L, int funcindex, int n);

        [DllImport(__DllName, EntryPoint = "lua_singlestep", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_singlestep(lua_State* L, int enabled);

        [DllImport(__DllName, EntryPoint = "lua_breakpoint", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_breakpoint(lua_State* L, int funcindex, int line, int enabled);

        [DllImport(__DllName, EntryPoint = "lua_getcoverage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_getcoverage(lua_State* L, int funcindex, void* context, delegate* unmanaged[Cdecl]<void*, byte*, int, int, int*, nuint, void> callback);

        [DllImport(__DllName, EntryPoint = "lua_debugtrace", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* lua_debugtrace(lua_State* L);

        [DllImport(__DllName, EntryPoint = "lua_callbacks", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_Callbacks* lua_callbacks(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaL_register", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_register(lua_State* L, byte* libname, luaL_Reg* l);

        [DllImport(__DllName, EntryPoint = "luaL_getmetafield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_getmetafield(lua_State* L, int obj, byte* e);

        [DllImport(__DllName, EntryPoint = "luaL_callmeta", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_callmeta(lua_State* L, int obj, byte* e);

        [DllImport(__DllName, EntryPoint = "luaL_checklstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* luaL_checklstring(lua_State* L, int numArg, nuint* l);

        [DllImport(__DllName, EntryPoint = "luaL_optlstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* luaL_optlstring(lua_State* L, int numArg, byte* def, nuint* l);

        [DllImport(__DllName, EntryPoint = "luaL_checknumber", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double luaL_checknumber(lua_State* L, int numArg);

        [DllImport(__DllName, EntryPoint = "luaL_optnumber", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double luaL_optnumber(lua_State* L, int nArg, double def);

        [DllImport(__DllName, EntryPoint = "luaL_checkboolean", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_checkboolean(lua_State* L, int narg);

        [DllImport(__DllName, EntryPoint = "luaL_optboolean", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_optboolean(lua_State* L, int narg, int def);

        [DllImport(__DllName, EntryPoint = "luaL_checkinteger", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_checkinteger(lua_State* L, int numArg);

        [DllImport(__DllName, EntryPoint = "luaL_optinteger", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_optinteger(lua_State* L, int nArg, int def);

        [DllImport(__DllName, EntryPoint = "luaL_checkunsigned", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint luaL_checkunsigned(lua_State* L, int numArg);

        [DllImport(__DllName, EntryPoint = "luaL_optunsigned", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint luaL_optunsigned(lua_State* L, int numArg, uint def);

        [DllImport(__DllName, EntryPoint = "luaL_checkvector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float* luaL_checkvector(lua_State* L, int narg);

        [DllImport(__DllName, EntryPoint = "luaL_optvector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float* luaL_optvector(lua_State* L, int narg, float* def);

        [DllImport(__DllName, EntryPoint = "luaL_checkstack", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_checkstack(lua_State* L, int sz, byte* msg);

        [DllImport(__DllName, EntryPoint = "luaL_checktype", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_checktype(lua_State* L, int narg, int t);

        [DllImport(__DllName, EntryPoint = "luaL_checkany", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_checkany(lua_State* L, int narg);

        [DllImport(__DllName, EntryPoint = "luaL_newmetatable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_newmetatable(lua_State* L, byte* tname);

        [DllImport(__DllName, EntryPoint = "luaL_checkudata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* luaL_checkudata(lua_State* L, int ud, byte* tname);

        [DllImport(__DllName, EntryPoint = "luaL_checkbuffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* luaL_checkbuffer(lua_State* L, int narg, nuint* len);

        [DllImport(__DllName, EntryPoint = "luaL_where", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_where(lua_State* L, int lvl);

        [DllImport(__DllName, EntryPoint = "luaL_checkoption", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_checkoption(lua_State* L, int narg, byte* def, byte** lst);

        [DllImport(__DllName, EntryPoint = "luaL_tolstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* luaL_tolstring(lua_State* L, int idx, nuint* len);

        [DllImport(__DllName, EntryPoint = "luaL_newstate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* luaL_newstate();

        [DllImport(__DllName, EntryPoint = "luaL_findtable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* luaL_findtable(lua_State* L, int idx, byte* fname, int szhint);

        [DllImport(__DllName, EntryPoint = "luaL_typename", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* luaL_typename(lua_State* L, int idx);

        [DllImport(__DllName, EntryPoint = "luaL_callyieldable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_callyieldable(lua_State* L, int nargs, int nresults);

        [DllImport(__DllName, EntryPoint = "luaL_traceback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_traceback(lua_State* L, lua_State* L1, byte* msg, int level);

        [DllImport(__DllName, EntryPoint = "luaL_buffinit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_buffinit(lua_State* L, luaL_Strbuf* B);

        [DllImport(__DllName, EntryPoint = "luaL_buffinitsize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* luaL_buffinitsize(lua_State* L, luaL_Strbuf* B, nuint size);

        [DllImport(__DllName, EntryPoint = "luaL_prepbuffsize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* luaL_prepbuffsize(luaL_Strbuf* B, nuint size);

        [DllImport(__DllName, EntryPoint = "luaL_addlstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_addlstring(luaL_Strbuf* B, byte* s, nuint l);

        [DllImport(__DllName, EntryPoint = "luaL_addvalue", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_addvalue(luaL_Strbuf* B);

        [DllImport(__DllName, EntryPoint = "luaL_addvalueany", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_addvalueany(luaL_Strbuf* B, int idx);

        [DllImport(__DllName, EntryPoint = "luaL_pushresult", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_pushresult(luaL_Strbuf* B);

        [DllImport(__DllName, EntryPoint = "luaL_pushresultsize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_pushresultsize(luaL_Strbuf* B, nuint size);

        [DllImport(__DllName, EntryPoint = "luaopen_base", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_base(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_coroutine", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_coroutine(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_table", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_table(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_os", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_os(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_string(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_bit32", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_bit32(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_buffer(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_utf8", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_utf8(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_math", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_math(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_debug", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_debug(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaopen_vector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_vector(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaL_openlibs", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_openlibs(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaL_sandbox", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_sandbox(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luaL_sandboxthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_sandboxthread(lua_State* L);

        [DllImport(__DllName, EntryPoint = "luau_compile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* luau_compile(byte* source, nuint size, lua_CompileOptions* options, nuint* outsize);

        [DllImport(__DllName, EntryPoint = "luau_set_compile_constant_nil", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luau_set_compile_constant_nil(void** constant);

        [DllImport(__DllName, EntryPoint = "luau_set_compile_constant_boolean", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luau_set_compile_constant_boolean(void** constant, int b);

        [DllImport(__DllName, EntryPoint = "luau_set_compile_constant_number", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luau_set_compile_constant_number(void** constant, double n);

        [DllImport(__DllName, EntryPoint = "luau_set_compile_constant_vector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luau_set_compile_constant_vector(void** constant, float x, float y, float z, float w);

        [DllImport(__DllName, EntryPoint = "luau_set_compile_constant_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luau_set_compile_constant_string(void** constant, byte* s, nuint l);

        [DllImport(__DllName, EntryPoint = "luau_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luau_free(void* ptr);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct lua_State
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct lua_Debug
    {
        public byte* name;
        public byte* what;
        public byte* source;
        public byte* short_src;
        public int linedefined;
        public int currentline;
        public byte nupvals;
        public byte nparams;
        public byte isvararg;
        public void* userdata;
        public fixed byte ssbuf[256];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct lua_Callbacks
    {
        public void* userdata;
        public delegate* unmanaged[Cdecl]<lua_State*, int, void> interrupt;
        public delegate* unmanaged[Cdecl]<lua_State*, int, void> panic;
        public delegate* unmanaged[Cdecl]<lua_State*, lua_State*, void> userthread;
        public delegate* unmanaged[Cdecl]<byte*, nuint, short> useratom;
        public delegate* unmanaged[Cdecl]<lua_State*, lua_Debug*, void> debugbreak;
        public delegate* unmanaged[Cdecl]<lua_State*, lua_Debug*, void> debugstep;
        public delegate* unmanaged[Cdecl]<lua_State*, lua_Debug*, void> debuginterrupt;
        public delegate* unmanaged[Cdecl]<lua_State*, void> debugprotectederror;
        public delegate* unmanaged[Cdecl]<lua_State*, nuint, nuint, void> onallocate;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct luaL_Reg
    {
        public byte* name;
        public delegate* unmanaged[Cdecl]<lua_State*, int> func;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct luaL_Strbuf
    {
        public byte* p;
        public byte* end;
        public lua_State* L;
        public TString* storage;
        public fixed byte buffer[512];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct lua_CompileOptions
    {
        public int optimizationLevel;
        public int debugLevel;
        public int typeInfoLevel;
        public int coverageLevel;
        public byte* vectorLib;
        public byte* vectorCtor;
        public byte* vectorType;
        public byte** mutableGlobals;
        public byte** userdataTypes;
        public byte** librariesWithKnownMembers;
        public delegate* unmanaged[Cdecl]<byte*, byte*, int> libraryMemberTypeCb;
        public delegate* unmanaged[Cdecl]<byte*, byte*, void**, void> libraryMemberConstantCb;
        public byte** disabledBuiltins;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TString
    {
        public byte _address;
    }


    public enum lua_Status : int
    {
        LUA_OK = 0,
        LUA_YIELD = 1,
        LUA_ERRRUN = 2,
        LUA_ERRSYNTAX = 3,
        LUA_ERRMEM = 4,
        LUA_ERRERR = 5,
        LUA_BREAK = 6,
    }

    public enum lua_CoStatus : int
    {
        LUA_CORUN = 0,
        LUA_COSUS = 1,
        LUA_CONOR = 2,
        LUA_COFIN = 3,
        LUA_COERR = 4,
    }

    public enum lua_Type : int
    {
        LUA_TNIL = 0,
        LUA_TBOOLEAN = 1,
        LUA_TLIGHTUSERDATA = 2,
        LUA_TNUMBER = 3,
        LUA_TVECTOR = 4,
        LUA_TSTRING = 5,
        LUA_TTABLE = 6,
        LUA_TFUNCTION = 7,
        LUA_TUSERDATA = 8,
        LUA_TTHREAD = 9,
        LUA_TBUFFER = 10,
        LUA_TPROTO = 11,
        LUA_TUPVAL = 12,
        LUA_TDEADKEY = 13,
    }

    public enum lua_GCOp : int
    {
        LUA_GCSTOP = 0,
        LUA_GCRESTART = 1,
        LUA_GCCOLLECT = 2,
        LUA_GCCOUNT = 3,
        LUA_GCCOUNTB = 4,
        LUA_GCISRUNNING = 5,
        LUA_GCSTEP = 6,
        LUA_GCSETGOAL = 7,
        LUA_GCSETSTEPMUL = 8,
        LUA_GCSETSTEPSIZE = 9,
    }


}
