/* automatically generated by rust-bindgen 0.72.1 */

pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_CXX26: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub const LUA_USE_LONGJMP: u32 = 0;
pub const LUA_IDSIZE: u32 = 256;
pub const LUA_MINSTACK: u32 = 20;
pub const LUAI_MAXCSTACK: u32 = 8000;
pub const LUAI_MAXCALLS: u32 = 20000;
pub const LUAI_MAXCCALLS: u32 = 200;
pub const LUA_BUFFERSIZE: u32 = 512;
pub const LUA_UTAG_LIMIT: u32 = 128;
pub const LUA_LUTAG_LIMIT: u32 = 128;
pub const LUA_SIZECLASSES: u32 = 40;
pub const LUA_MEMORY_CATEGORIES: u32 = 256;
pub const LUA_EXECUTION_CALLBACK_STORAGE: u32 = 512;
pub const LUA_MINSTRTABSIZE: u32 = 32;
pub const LUA_MAXCAPTURES: u32 = 32;
pub const LUA_VECTOR_SIZE: u32 = 3;
pub const LUA_EXTRA_SIZE: u32 = 1;
pub const LUA_MULTRET: i32 = -1;
pub const LUA_REGISTRYINDEX: i32 = -10000;
pub const LUA_ENVIRONINDEX: i32 = -10001;
pub const LUA_GLOBALSINDEX: i32 = -10002;
pub const LUA_TNONE: i32 = -1;
pub const LUA_NOREF: i32 = -1;
pub const LUA_REFNIL: u32 = 0;
pub const LUA_COLIBNAME: &[u8; 10] = b"coroutine\0";
pub const LUA_TABLIBNAME: &[u8; 6] = b"table\0";
pub const LUA_OSLIBNAME: &[u8; 3] = b"os\0";
pub const LUA_STRLIBNAME: &[u8; 7] = b"string\0";
pub const LUA_BITLIBNAME: &[u8; 6] = b"bit32\0";
pub const LUA_BUFFERLIBNAME: &[u8; 7] = b"buffer\0";
pub const LUA_UTF8LIBNAME: &[u8; 5] = b"utf8\0";
pub const LUA_MATHLIBNAME: &[u8; 5] = b"math\0";
pub const LUA_DBLIBNAME: &[u8; 6] = b"debug\0";
pub const LUA_VECLIBNAME: &[u8; 7] = b"vector\0";
pub type __gnuc_va_list = __builtin_va_list;
pub type va_list = __builtin_va_list;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type max_align_t = f64;
unsafe extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type __vcrt_bool = bool;
unsafe extern "C" {
    pub fn __security_init_cookie();
}
unsafe extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
unsafe extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
unsafe extern "C" {
    pub static mut __security_cookie: usize;
}
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum lua_Status {
    LUA_OK = 0,
    LUA_YIELD = 1,
    LUA_ERRRUN = 2,
    LUA_ERRSYNTAX = 3,
    LUA_ERRMEM = 4,
    LUA_ERRERR = 5,
    LUA_BREAK = 6,
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum lua_CoStatus {
    LUA_CORUN = 0,
    LUA_COSUS = 1,
    LUA_CONOR = 2,
    LUA_COFIN = 3,
    LUA_COERR = 4,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_State {
    _unused: [u8; 0],
}
pub type lua_CFunction =
    ::std::option::Option<unsafe extern "C" fn(L: *mut lua_State) -> ::std::os::raw::c_int>;
pub type lua_Continuation = ::std::option::Option<
    unsafe extern "C" fn(L: *mut lua_State, status: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
>;
pub type lua_Alloc = ::std::option::Option<
    unsafe extern "C" fn(
        ud: *mut ::std::os::raw::c_void,
        ptr: *mut ::std::os::raw::c_void,
        osize: usize,
        nsize: usize,
    ) -> *mut ::std::os::raw::c_void,
>;
impl lua_Type {
    pub const LUA_T_COUNT: lua_Type = lua_Type::LUA_TPROTO;
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum lua_Type {
    LUA_TNIL = 0,
    LUA_TBOOLEAN = 1,
    LUA_TLIGHTUSERDATA = 2,
    LUA_TNUMBER = 3,
    LUA_TVECTOR = 4,
    LUA_TSTRING = 5,
    LUA_TTABLE = 6,
    LUA_TFUNCTION = 7,
    LUA_TUSERDATA = 8,
    LUA_TTHREAD = 9,
    LUA_TBUFFER = 10,
    LUA_TPROTO = 11,
    LUA_TUPVAL = 12,
    LUA_TDEADKEY = 13,
}
pub type lua_Number = f64;
pub type lua_Integer = ::std::os::raw::c_int;
pub type lua_Unsigned = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn lua_newstate(f: lua_Alloc, ud: *mut ::std::os::raw::c_void) -> *mut lua_State;
}
unsafe extern "C" {
    pub fn lua_close(L: *mut lua_State);
}
unsafe extern "C" {
    pub fn lua_newthread(L: *mut lua_State) -> *mut lua_State;
}
unsafe extern "C" {
    pub fn lua_mainthread(L: *mut lua_State) -> *mut lua_State;
}
unsafe extern "C" {
    pub fn lua_resetthread(L: *mut lua_State);
}
unsafe extern "C" {
    pub fn lua_isthreadreset(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_absindex(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_gettop(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_settop(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_pushvalue(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_remove(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_insert(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_replace(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_checkstack(L: *mut lua_State, sz: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_rawcheckstack(L: *mut lua_State, sz: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_xmove(from: *mut lua_State, to: *mut lua_State, n: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_xpush(from: *mut lua_State, to: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_isnumber(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_isstring(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_iscfunction(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_isLfunction(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_isuserdata(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_type(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_typename(
        L: *mut lua_State,
        tp: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_equal(
        L: *mut lua_State,
        idx1: ::std::os::raw::c_int,
        idx2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_rawequal(
        L: *mut lua_State,
        idx1: ::std::os::raw::c_int,
        idx2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_lessthan(
        L: *mut lua_State,
        idx1: ::std::os::raw::c_int,
        idx2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_tonumberx(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        isnum: *mut ::std::os::raw::c_int,
    ) -> f64;
}
unsafe extern "C" {
    pub fn lua_tointegerx(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        isnum: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_tounsignedx(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        isnum: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn lua_tovector(L: *mut lua_State, idx: ::std::os::raw::c_int) -> *const f32;
}
unsafe extern "C" {
    pub fn lua_toboolean(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_tolstring(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        len: *mut usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_tostringatom(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        atom: *mut ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_tolstringatom(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        len: *mut usize,
        atom: *mut ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_namecallatom(
        L: *mut lua_State,
        atom: *mut ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_objlen(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_tocfunction(L: *mut lua_State, idx: ::std::os::raw::c_int) -> lua_CFunction;
}
unsafe extern "C" {
    pub fn lua_tolightuserdata(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_tolightuserdatatagged(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        tag: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_touserdata(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_touserdatatagged(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        tag: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_userdatatag(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_lightuserdatatag(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_tothread(L: *mut lua_State, idx: ::std::os::raw::c_int) -> *mut lua_State;
}
unsafe extern "C" {
    pub fn lua_tobuffer(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        len: *mut usize,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_topointer(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_pushnil(L: *mut lua_State);
}
unsafe extern "C" {
    pub fn lua_pushnumber(L: *mut lua_State, n: f64);
}
unsafe extern "C" {
    pub fn lua_pushinteger(L: *mut lua_State, n: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_pushunsigned(L: *mut lua_State, n: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn lua_pushvector(L: *mut lua_State, x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn lua_pushlstring(L: *mut lua_State, s: *const ::std::os::raw::c_char, l: usize);
}
unsafe extern "C" {
    pub fn lua_pushstring(L: *mut lua_State, s: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn lua_pushvfstring(
        L: *mut lua_State,
        fmt: *const ::std::os::raw::c_char,
        argp: va_list,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_pushfstringL(
        L: *mut lua_State,
        fmt: *const ::std::os::raw::c_char,
        ...
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_pushcclosurek(
        L: *mut lua_State,
        fn_: lua_CFunction,
        debugname: *const ::std::os::raw::c_char,
        nup: ::std::os::raw::c_int,
        cont: lua_Continuation,
    );
}
unsafe extern "C" {
    pub fn lua_pushboolean(L: *mut lua_State, b: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_pushthread(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_pushlightuserdatatagged(
        L: *mut lua_State,
        p: *mut ::std::os::raw::c_void,
        tag: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn lua_newuserdatatagged(
        L: *mut lua_State,
        sz: usize,
        tag: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_newuserdatataggedwithmetatable(
        L: *mut lua_State,
        sz: usize,
        tag: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_newuserdatadtor(
        L: *mut lua_State,
        sz: usize,
        dtor: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_newbuffer(L: *mut lua_State, sz: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_gettable(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_getfield(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        k: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_rawgetfield(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        k: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_rawget(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_rawgeti(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_rawgetptagged(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        p: *mut ::std::os::raw::c_void,
        tag: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_createtable(
        L: *mut lua_State,
        narr: ::std::os::raw::c_int,
        nrec: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn lua_setreadonly(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        enabled: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn lua_getreadonly(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_setsafeenv(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        enabled: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn lua_getmetatable(
        L: *mut lua_State,
        objindex: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_getfenv(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_settable(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_setfield(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        k: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn lua_rawsetfield(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        k: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn lua_rawset(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_rawseti(L: *mut lua_State, idx: ::std::os::raw::c_int, n: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_rawsetptagged(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        p: *mut ::std::os::raw::c_void,
        tag: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn lua_setmetatable(
        L: *mut lua_State,
        objindex: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_setfenv(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luau_load(
        L: *mut lua_State,
        chunkname: *const ::std::os::raw::c_char,
        data: *const ::std::os::raw::c_char,
        size: usize,
        env: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_call(
        L: *mut lua_State,
        nargs: ::std::os::raw::c_int,
        nresults: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn lua_pcall(
        L: *mut lua_State,
        nargs: ::std::os::raw::c_int,
        nresults: ::std::os::raw::c_int,
        errfunc: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_cpcall(
        L: *mut lua_State,
        func: lua_CFunction,
        ud: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_yield(L: *mut lua_State, nresults: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_break(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_resume(
        L: *mut lua_State,
        from: *mut lua_State,
        narg: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_resumeerror(L: *mut lua_State, from: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_status(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_isyieldable(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_getthreaddata(L: *mut lua_State) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn lua_setthreaddata(L: *mut lua_State, data: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn lua_costatus(L: *mut lua_State, co: *mut lua_State) -> ::std::os::raw::c_int;
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum lua_GCOp {
    LUA_GCSTOP = 0,
    LUA_GCRESTART = 1,
    LUA_GCCOLLECT = 2,
    LUA_GCCOUNT = 3,
    LUA_GCCOUNTB = 4,
    LUA_GCISRUNNING = 5,
    LUA_GCSTEP = 6,
    LUA_GCSETGOAL = 7,
    LUA_GCSETSTEPMUL = 8,
    LUA_GCSETSTEPSIZE = 9,
}
unsafe extern "C" {
    pub fn lua_gc(
        L: *mut lua_State,
        what: ::std::os::raw::c_int,
        data: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_setmemcat(L: *mut lua_State, category: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_totalbytes(L: *mut lua_State, category: ::std::os::raw::c_int) -> usize;
}
unsafe extern "C" {
    pub fn lua_error(L: *mut lua_State) -> !;
}
unsafe extern "C" {
    pub fn lua_next(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_rawiter(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        iter: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_concat(L: *mut lua_State, n: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_encodepointer(L: *mut lua_State, p: usize) -> usize;
}
unsafe extern "C" {
    pub fn lua_clock() -> f64;
}
unsafe extern "C" {
    pub fn lua_setuserdatatag(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        tag: ::std::os::raw::c_int,
    );
}
pub type lua_Destructor = ::std::option::Option<
    unsafe extern "C" fn(L: *mut lua_State, userdata: *mut ::std::os::raw::c_void),
>;
unsafe extern "C" {
    pub fn lua_setuserdatadtor(L: *mut lua_State, tag: ::std::os::raw::c_int, dtor: lua_Destructor);
}
unsafe extern "C" {
    pub fn lua_getuserdatadtor(L: *mut lua_State, tag: ::std::os::raw::c_int) -> lua_Destructor;
}
unsafe extern "C" {
    pub fn lua_setuserdatametatable(L: *mut lua_State, tag: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_getuserdatametatable(L: *mut lua_State, tag: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_setlightuserdataname(
        L: *mut lua_State,
        tag: ::std::os::raw::c_int,
        name: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn lua_getlightuserdataname(
        L: *mut lua_State,
        tag: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_clonefunction(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_cleartable(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_clonetable(L: *mut lua_State, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_getallocf(L: *mut lua_State, ud: *mut *mut ::std::os::raw::c_void) -> lua_Alloc;
}
unsafe extern "C" {
    pub fn lua_ref(L: *mut lua_State, idx: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_unref(L: *mut lua_State, ref_: ::std::os::raw::c_int);
}
pub type lua_Hook =
    ::std::option::Option<unsafe extern "C" fn(L: *mut lua_State, ar: *mut lua_Debug)>;
unsafe extern "C" {
    pub fn lua_stackdepth(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_getinfo(
        L: *mut lua_State,
        level: ::std::os::raw::c_int,
        what: *const ::std::os::raw::c_char,
        ar: *mut lua_Debug,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_getargument(
        L: *mut lua_State,
        level: ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lua_getlocal(
        L: *mut lua_State,
        level: ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_setlocal(
        L: *mut lua_State,
        level: ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_getupvalue(
        L: *mut lua_State,
        funcindex: ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_setupvalue(
        L: *mut lua_State,
        funcindex: ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn lua_singlestep(L: *mut lua_State, enabled: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn lua_breakpoint(
        L: *mut lua_State,
        funcindex: ::std::os::raw::c_int,
        line: ::std::os::raw::c_int,
        enabled: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub type lua_Coverage = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut ::std::os::raw::c_void,
        function: *const ::std::os::raw::c_char,
        linedefined: ::std::os::raw::c_int,
        depth: ::std::os::raw::c_int,
        hits: *const ::std::os::raw::c_int,
        size: usize,
    ),
>;
unsafe extern "C" {
    pub fn lua_getcoverage(
        L: *mut lua_State,
        funcindex: ::std::os::raw::c_int,
        context: *mut ::std::os::raw::c_void,
        callback: lua_Coverage,
    );
}
unsafe extern "C" {
    pub fn lua_debugtrace(L: *mut lua_State) -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_Debug {
    pub name: *const ::std::os::raw::c_char,
    pub what: *const ::std::os::raw::c_char,
    pub source: *const ::std::os::raw::c_char,
    pub short_src: *const ::std::os::raw::c_char,
    pub linedefined: ::std::os::raw::c_int,
    pub currentline: ::std::os::raw::c_int,
    pub nupvals: ::std::os::raw::c_uchar,
    pub nparams: ::std::os::raw::c_uchar,
    pub isvararg: ::std::os::raw::c_char,
    pub userdata: *mut ::std::os::raw::c_void,
    pub ssbuf: [::std::os::raw::c_char; 256usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lua_Debug"][::std::mem::size_of::<lua_Debug>() - 312usize];
    ["Alignment of lua_Debug"][::std::mem::align_of::<lua_Debug>() - 8usize];
    ["Offset of field: lua_Debug::name"][::std::mem::offset_of!(lua_Debug, name) - 0usize];
    ["Offset of field: lua_Debug::what"][::std::mem::offset_of!(lua_Debug, what) - 8usize];
    ["Offset of field: lua_Debug::source"][::std::mem::offset_of!(lua_Debug, source) - 16usize];
    ["Offset of field: lua_Debug::short_src"]
        [::std::mem::offset_of!(lua_Debug, short_src) - 24usize];
    ["Offset of field: lua_Debug::linedefined"]
        [::std::mem::offset_of!(lua_Debug, linedefined) - 32usize];
    ["Offset of field: lua_Debug::currentline"]
        [::std::mem::offset_of!(lua_Debug, currentline) - 36usize];
    ["Offset of field: lua_Debug::nupvals"][::std::mem::offset_of!(lua_Debug, nupvals) - 40usize];
    ["Offset of field: lua_Debug::nparams"][::std::mem::offset_of!(lua_Debug, nparams) - 41usize];
    ["Offset of field: lua_Debug::isvararg"][::std::mem::offset_of!(lua_Debug, isvararg) - 42usize];
    ["Offset of field: lua_Debug::userdata"][::std::mem::offset_of!(lua_Debug, userdata) - 48usize];
    ["Offset of field: lua_Debug::ssbuf"][::std::mem::offset_of!(lua_Debug, ssbuf) - 56usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_Callbacks {
    pub userdata: *mut ::std::os::raw::c_void,
    pub interrupt:
        ::std::option::Option<unsafe extern "C" fn(L: *mut lua_State, gc: ::std::os::raw::c_int)>,
    pub panic: ::std::option::Option<
        unsafe extern "C" fn(L: *mut lua_State, errcode: ::std::os::raw::c_int),
    >,
    pub userthread:
        ::std::option::Option<unsafe extern "C" fn(LP: *mut lua_State, L: *mut lua_State)>,
    pub useratom: ::std::option::Option<
        unsafe extern "C" fn(s: *const ::std::os::raw::c_char, l: usize) -> i16,
    >,
    pub debugbreak:
        ::std::option::Option<unsafe extern "C" fn(L: *mut lua_State, ar: *mut lua_Debug)>,
    pub debugstep:
        ::std::option::Option<unsafe extern "C" fn(L: *mut lua_State, ar: *mut lua_Debug)>,
    pub debuginterrupt:
        ::std::option::Option<unsafe extern "C" fn(L: *mut lua_State, ar: *mut lua_Debug)>,
    pub debugprotectederror: ::std::option::Option<unsafe extern "C" fn(L: *mut lua_State)>,
    pub onallocate:
        ::std::option::Option<unsafe extern "C" fn(L: *mut lua_State, osize: usize, nsize: usize)>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lua_Callbacks"][::std::mem::size_of::<lua_Callbacks>() - 80usize];
    ["Alignment of lua_Callbacks"][::std::mem::align_of::<lua_Callbacks>() - 8usize];
    ["Offset of field: lua_Callbacks::userdata"]
        [::std::mem::offset_of!(lua_Callbacks, userdata) - 0usize];
    ["Offset of field: lua_Callbacks::interrupt"]
        [::std::mem::offset_of!(lua_Callbacks, interrupt) - 8usize];
    ["Offset of field: lua_Callbacks::panic"]
        [::std::mem::offset_of!(lua_Callbacks, panic) - 16usize];
    ["Offset of field: lua_Callbacks::userthread"]
        [::std::mem::offset_of!(lua_Callbacks, userthread) - 24usize];
    ["Offset of field: lua_Callbacks::useratom"]
        [::std::mem::offset_of!(lua_Callbacks, useratom) - 32usize];
    ["Offset of field: lua_Callbacks::debugbreak"]
        [::std::mem::offset_of!(lua_Callbacks, debugbreak) - 40usize];
    ["Offset of field: lua_Callbacks::debugstep"]
        [::std::mem::offset_of!(lua_Callbacks, debugstep) - 48usize];
    ["Offset of field: lua_Callbacks::debuginterrupt"]
        [::std::mem::offset_of!(lua_Callbacks, debuginterrupt) - 56usize];
    ["Offset of field: lua_Callbacks::debugprotectederror"]
        [::std::mem::offset_of!(lua_Callbacks, debugprotectederror) - 64usize];
    ["Offset of field: lua_Callbacks::onallocate"]
        [::std::mem::offset_of!(lua_Callbacks, onallocate) - 72usize];
};
unsafe extern "C" {
    pub fn lua_callbacks(L: *mut lua_State) -> *mut lua_Callbacks;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct luaL_Reg {
    pub name: *const ::std::os::raw::c_char,
    pub func: lua_CFunction,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of luaL_Reg"][::std::mem::size_of::<luaL_Reg>() - 16usize];
    ["Alignment of luaL_Reg"][::std::mem::align_of::<luaL_Reg>() - 8usize];
    ["Offset of field: luaL_Reg::name"][::std::mem::offset_of!(luaL_Reg, name) - 0usize];
    ["Offset of field: luaL_Reg::func"][::std::mem::offset_of!(luaL_Reg, func) - 8usize];
};
unsafe extern "C" {
    pub fn luaL_register(
        L: *mut lua_State,
        libname: *const ::std::os::raw::c_char,
        l: *const luaL_Reg,
    );
}
unsafe extern "C" {
    pub fn luaL_getmetafield(
        L: *mut lua_State,
        obj: ::std::os::raw::c_int,
        e: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_callmeta(
        L: *mut lua_State,
        obj: ::std::os::raw::c_int,
        e: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_typeerrorL(
        L: *mut lua_State,
        narg: ::std::os::raw::c_int,
        tname: *const ::std::os::raw::c_char,
    ) -> !;
}
unsafe extern "C" {
    pub fn luaL_argerrorL(
        L: *mut lua_State,
        narg: ::std::os::raw::c_int,
        extramsg: *const ::std::os::raw::c_char,
    ) -> !;
}
unsafe extern "C" {
    pub fn luaL_checklstring(
        L: *mut lua_State,
        numArg: ::std::os::raw::c_int,
        l: *mut usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn luaL_optlstring(
        L: *mut lua_State,
        numArg: ::std::os::raw::c_int,
        def: *const ::std::os::raw::c_char,
        l: *mut usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn luaL_checknumber(L: *mut lua_State, numArg: ::std::os::raw::c_int) -> f64;
}
unsafe extern "C" {
    pub fn luaL_optnumber(L: *mut lua_State, nArg: ::std::os::raw::c_int, def: f64) -> f64;
}
unsafe extern "C" {
    pub fn luaL_checkboolean(
        L: *mut lua_State,
        narg: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_optboolean(
        L: *mut lua_State,
        narg: ::std::os::raw::c_int,
        def: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_checkinteger(
        L: *mut lua_State,
        numArg: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_optinteger(
        L: *mut lua_State,
        nArg: ::std::os::raw::c_int,
        def: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_checkunsigned(
        L: *mut lua_State,
        numArg: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn luaL_optunsigned(
        L: *mut lua_State,
        numArg: ::std::os::raw::c_int,
        def: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn luaL_checkvector(L: *mut lua_State, narg: ::std::os::raw::c_int) -> *const f32;
}
unsafe extern "C" {
    pub fn luaL_optvector(
        L: *mut lua_State,
        narg: ::std::os::raw::c_int,
        def: *const f32,
    ) -> *const f32;
}
unsafe extern "C" {
    pub fn luaL_checkstack(
        L: *mut lua_State,
        sz: ::std::os::raw::c_int,
        msg: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn luaL_checktype(L: *mut lua_State, narg: ::std::os::raw::c_int, t: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn luaL_checkany(L: *mut lua_State, narg: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn luaL_newmetatable(
        L: *mut lua_State,
        tname: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_checkudata(
        L: *mut lua_State,
        ud: ::std::os::raw::c_int,
        tname: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn luaL_checkbuffer(
        L: *mut lua_State,
        narg: ::std::os::raw::c_int,
        len: *mut usize,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn luaL_where(L: *mut lua_State, lvl: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn luaL_errorL(L: *mut lua_State, fmt: *const ::std::os::raw::c_char, ...) -> !;
}
unsafe extern "C" {
    pub fn luaL_checkoption(
        L: *mut lua_State,
        narg: ::std::os::raw::c_int,
        def: *const ::std::os::raw::c_char,
        lst: *const *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_tolstring(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        len: *mut usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn luaL_newstate() -> *mut lua_State;
}
unsafe extern "C" {
    pub fn luaL_findtable(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
        fname: *const ::std::os::raw::c_char,
        szhint: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn luaL_typename(
        L: *mut lua_State,
        idx: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn luaL_callyieldable(
        L: *mut lua_State,
        nargs: ::std::os::raw::c_int,
        nresults: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_traceback(
        L: *mut lua_State,
        L1: *mut lua_State,
        msg: *const ::std::os::raw::c_char,
        level: ::std::os::raw::c_int,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct luaL_Strbuf {
    pub p: *mut ::std::os::raw::c_char,
    pub end: *mut ::std::os::raw::c_char,
    pub L: *mut lua_State,
    pub storage: *mut TString,
    pub buffer: [::std::os::raw::c_char; 512usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of luaL_Strbuf"][::std::mem::size_of::<luaL_Strbuf>() - 544usize];
    ["Alignment of luaL_Strbuf"][::std::mem::align_of::<luaL_Strbuf>() - 8usize];
    ["Offset of field: luaL_Strbuf::p"][::std::mem::offset_of!(luaL_Strbuf, p) - 0usize];
    ["Offset of field: luaL_Strbuf::end"][::std::mem::offset_of!(luaL_Strbuf, end) - 8usize];
    ["Offset of field: luaL_Strbuf::L"][::std::mem::offset_of!(luaL_Strbuf, L) - 16usize];
    ["Offset of field: luaL_Strbuf::storage"]
        [::std::mem::offset_of!(luaL_Strbuf, storage) - 24usize];
    ["Offset of field: luaL_Strbuf::buffer"][::std::mem::offset_of!(luaL_Strbuf, buffer) - 32usize];
};
pub type luaL_Buffer = luaL_Strbuf;
unsafe extern "C" {
    pub fn luaL_buffinit(L: *mut lua_State, B: *mut luaL_Strbuf);
}
unsafe extern "C" {
    pub fn luaL_buffinitsize(
        L: *mut lua_State,
        B: *mut luaL_Strbuf,
        size: usize,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn luaL_prepbuffsize(B: *mut luaL_Buffer, size: usize) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn luaL_addlstring(B: *mut luaL_Strbuf, s: *const ::std::os::raw::c_char, l: usize);
}
unsafe extern "C" {
    pub fn luaL_addvalue(B: *mut luaL_Strbuf);
}
unsafe extern "C" {
    pub fn luaL_addvalueany(B: *mut luaL_Strbuf, idx: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn luaL_pushresult(B: *mut luaL_Strbuf);
}
unsafe extern "C" {
    pub fn luaL_pushresultsize(B: *mut luaL_Strbuf, size: usize);
}
unsafe extern "C" {
    pub fn luaopen_base(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_coroutine(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_table(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_os(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_string(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_bit32(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_buffer(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_utf8(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_math(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_debug(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaopen_vector(L: *mut lua_State) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn luaL_openlibs(L: *mut lua_State);
}
unsafe extern "C" {
    pub fn luaL_sandbox(L: *mut lua_State);
}
unsafe extern "C" {
    pub fn luaL_sandboxthread(L: *mut lua_State);
}
pub type lua_CompileConstant = *mut ::std::os::raw::c_void;
pub type lua_LibraryMemberTypeCallback = ::std::option::Option<
    unsafe extern "C" fn(
        library: *const ::std::os::raw::c_char,
        member: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
>;
pub type lua_LibraryMemberConstantCallback = ::std::option::Option<
    unsafe extern "C" fn(
        library: *const ::std::os::raw::c_char,
        member: *const ::std::os::raw::c_char,
        constant: *mut lua_CompileConstant,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_CompileOptions {
    pub optimizationLevel: ::std::os::raw::c_int,
    pub debugLevel: ::std::os::raw::c_int,
    pub typeInfoLevel: ::std::os::raw::c_int,
    pub coverageLevel: ::std::os::raw::c_int,
    pub vectorLib: *const ::std::os::raw::c_char,
    pub vectorCtor: *const ::std::os::raw::c_char,
    pub vectorType: *const ::std::os::raw::c_char,
    pub mutableGlobals: *const *const ::std::os::raw::c_char,
    pub userdataTypes: *const *const ::std::os::raw::c_char,
    pub librariesWithKnownMembers: *const *const ::std::os::raw::c_char,
    pub libraryMemberTypeCb: lua_LibraryMemberTypeCallback,
    pub libraryMemberConstantCb: lua_LibraryMemberConstantCallback,
    pub disabledBuiltins: *const *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lua_CompileOptions"][::std::mem::size_of::<lua_CompileOptions>() - 88usize];
    ["Alignment of lua_CompileOptions"][::std::mem::align_of::<lua_CompileOptions>() - 8usize];
    ["Offset of field: lua_CompileOptions::optimizationLevel"]
        [::std::mem::offset_of!(lua_CompileOptions, optimizationLevel) - 0usize];
    ["Offset of field: lua_CompileOptions::debugLevel"]
        [::std::mem::offset_of!(lua_CompileOptions, debugLevel) - 4usize];
    ["Offset of field: lua_CompileOptions::typeInfoLevel"]
        [::std::mem::offset_of!(lua_CompileOptions, typeInfoLevel) - 8usize];
    ["Offset of field: lua_CompileOptions::coverageLevel"]
        [::std::mem::offset_of!(lua_CompileOptions, coverageLevel) - 12usize];
    ["Offset of field: lua_CompileOptions::vectorLib"]
        [::std::mem::offset_of!(lua_CompileOptions, vectorLib) - 16usize];
    ["Offset of field: lua_CompileOptions::vectorCtor"]
        [::std::mem::offset_of!(lua_CompileOptions, vectorCtor) - 24usize];
    ["Offset of field: lua_CompileOptions::vectorType"]
        [::std::mem::offset_of!(lua_CompileOptions, vectorType) - 32usize];
    ["Offset of field: lua_CompileOptions::mutableGlobals"]
        [::std::mem::offset_of!(lua_CompileOptions, mutableGlobals) - 40usize];
    ["Offset of field: lua_CompileOptions::userdataTypes"]
        [::std::mem::offset_of!(lua_CompileOptions, userdataTypes) - 48usize];
    ["Offset of field: lua_CompileOptions::librariesWithKnownMembers"]
        [::std::mem::offset_of!(lua_CompileOptions, librariesWithKnownMembers) - 56usize];
    ["Offset of field: lua_CompileOptions::libraryMemberTypeCb"]
        [::std::mem::offset_of!(lua_CompileOptions, libraryMemberTypeCb) - 64usize];
    ["Offset of field: lua_CompileOptions::libraryMemberConstantCb"]
        [::std::mem::offset_of!(lua_CompileOptions, libraryMemberConstantCb) - 72usize];
    ["Offset of field: lua_CompileOptions::disabledBuiltins"]
        [::std::mem::offset_of!(lua_CompileOptions, disabledBuiltins) - 80usize];
};
unsafe extern "C" {
    pub fn luau_compile(
        source: *const ::std::os::raw::c_char,
        size: usize,
        options: *mut lua_CompileOptions,
        outsize: *mut usize,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn luau_set_compile_constant_nil(constant: *mut lua_CompileConstant);
}
unsafe extern "C" {
    pub fn luau_set_compile_constant_boolean(
        constant: *mut lua_CompileConstant,
        b: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn luau_set_compile_constant_number(constant: *mut lua_CompileConstant, n: f64);
}
unsafe extern "C" {
    pub fn luau_set_compile_constant_vector(
        constant: *mut lua_CompileConstant,
        x: f32,
        y: f32,
        z: f32,
        w: f32,
    );
}
unsafe extern "C" {
    pub fn luau_set_compile_constant_string(
        constant: *mut lua_CompileConstant,
        s: *const ::std::os::raw::c_char,
        l: usize,
    );
}
unsafe extern "C" {
    pub fn luau_free(ptr: *mut ::std::os::raw::c_void);
}
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TString {
    pub _address: u8,
}
